# Generated by Django 6.1.1 on 2026-10-08 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor_name",
                    models.CharField(
                        help_text="Kept when the user is deleted.", max_length=150
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("target", models.CharField(blank=True, max_length=200)),
                ("detail", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LoginEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("failed", "Failed login"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, help_text="The name that was typed.", max_length=150
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("session_key", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="login_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["kind", "-created_at"],
                        name="ops_loginev_kind_927fb6_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TaskRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=64, unique=True)),
                ("task_name", models.CharField(max_length=200)),
                (
                    "label",
                    models.CharField(
                        help_text="The name that the pages show. For a command: command: <name>.",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting"),
                            ("started", "Running"),
                            ("success", "Done"),
                            ("failure", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[("auto", "Automatic"), ("manual", "Manual")],
                        default="auto",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("worker", models.CharField(blank=True, max_length=200)),
                ("args", models.CharField(blank=True, max_length=500)),
                (
                    "result",
                    models.TextField(
                        blank=True, help_text="What the task returned. It can be cut."
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True,
                        help_text="The error and the traceback. It can be cut.",
                    ),
                ),
                (
                    "output",
                    models.TextField(
                        blank=True, help_text="The text that a command printed."
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["label", "-created_at"],
                        name="ops_taskrun_label_ec3675_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="ops_taskrun_status_6cb8fd_idx",
                    ),
                ],
            },
        ),
    ]
