# Generated by Django 6.1.1 on 2026-10-05 01:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_date",
                    models.DateField(
                        help_text="The trading day that we predict.", unique=True
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("up", "Up"), ("down", "Down"), ("flat", "Flat")],
                        max_length=10,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        help_text="How strong the signal is, from 0 to 1. It is NOT a measured probability. Compare it with the accuracy numbers (python manage.py prediction_stats).",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("score", models.FloatField(help_text="From -1 (down) to 1 (up).")),
                (
                    "news_score",
                    models.FloatField(
                        blank=True, help_text="Part of the score from news.", null=True
                    ),
                ),
                (
                    "global_score",
                    models.FloatField(
                        blank=True,
                        help_text="Part of the score from global markets.",
                        null=True,
                    ),
                ),
                (
                    "news_articles",
                    models.PositiveIntegerField(
                        default=0, help_text="Articles in the news score."
                    ),
                ),
                (
                    "inputs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="All the numbers that gave this prediction.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actual_change_pct", models.FloatField(blank=True, null=True)),
                (
                    "actual_direction",
                    models.CharField(
                        blank=True,
                        choices=[("up", "Up"), ("down", "Down"), ("flat", "Flat")],
                        max_length=10,
                    ),
                ),
                (
                    "correct",
                    models.BooleanField(
                        blank=True,
                        help_text="Empty means no result yet, or no trading session on that day.",
                        null=True,
                    ),
                ),
                ("evaluated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-target_date"],
            },
        ),
        migrations.CreateModel(
            name="IndexQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="The Yahoo Finance symbol, for example ^NSEI.",
                        max_length=20,
                    ),
                ),
                (
                    "day",
                    models.DateField(
                        help_text="The trading day. This is the local date of the exchange."
                    ),
                ),
                ("close", models.FloatField()),
                (
                    "change_pct",
                    models.FloatField(
                        blank=True,
                        help_text="Change from the close of the day before, in percent.",
                        null=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When we last saved this row. A row that is older than the close of the market can hold a price from the middle of the session.",
                    ),
                ),
            ],
            options={
                "ordering": ["symbol", "-day"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("symbol", "day"), name="unique_quote_symbol_day"
                    )
                ],
            },
        ),
    ]
