# Generated by Django 6.1.1 on 2026-10-09 05:59

from django.db import migrations, models


INSTRUMENTS = [('^NSEI', 'Nifty 50', 'target', 0.0, 1.0), ('^BSESN', 'Sensex', 'index', 0.0, 1.0), ('^GSPC', 'S&P 500', 'cue', 0.3, 2.0), ('^IXIC', 'Nasdaq', 'cue', 0.15, 2.5), ('^N225', 'Nikkei 225', 'cue', 0.1, 2.5), ('^HSI', 'Hang Seng', 'cue', 0.1, 2.5), ('BZ=F', 'Brent crude', 'cue', -0.15, 3.0), ('USDINR=X', 'USD/INR', 'cue', -0.1, 0.6), ('^INDIAVIX', 'India VIX', 'cue', -0.1, 8.0)]


def seed_instruments(apps, schema_editor):
    """Save the first instruments. After this, they are edited on the Ops pages."""
    Instrument = apps.get_model("markets", "Instrument")
    for symbol, name, kind, weight, scale in INSTRUMENTS:
        Instrument.objects.get_or_create(
            symbol=symbol,
            defaults={"name": name, "kind": kind, "weight": weight, "scale": scale},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="The Yahoo Finance symbol.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("target", "Target index"),
                            ("index", "Index"),
                            ("cue", "Global cue"),
                        ],
                        default="cue",
                        max_length=10,
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        default=0.0,
                        help_text="For a cue: from -1 to 1. Not used for others.",
                    ),
                ),
                (
                    "scale",
                    models.FloatField(
                        default=1.0,
                        help_text="For a cue: the move in % that is a full signal.",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "target")),
                        fields=("kind",),
                        name="one_target_instrument",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_instruments, migrations.RunPython.noop),
    ]
