# Generated by Django 6.1.1 on 2026-10-04 07:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Source name, for example Moneycontrol.",
                        max_length=100,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("url", models.URLField(max_length=1000, unique=True)),
                (
                    "text",
                    models.TextField(
                        blank=True, help_text="Full article text, if it was scraped."
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sentiment_score",
                    models.FloatField(
                        blank=True,
                        help_text="From -1 (very negative) to 1 (very positive).",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-1.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("sentiment_reason", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-published_at", "-fetched_at"],
            },
        ),
    ]
