# Generated by Django 6.1.1 on 2026-10-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="summary",
            field=models.TextField(
                blank=True, help_text="Short text from the RSS feed."
            ),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="text_scraped_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When we tried to scrape the full text. Empty means not tried yet.",
                null=True,
            ),
        ),
    ]
