# Generated by Django 6.1.1 on 2026-10-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_aliases_alter_company_screener_data"),
        ("news", "0002_news_text_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="companies",
            field=models.ManyToManyField(
                blank=True, related_name="news_articles", to="companies.company"
            ),
        ),
    ]
