# Generated by Django 6.1.1 on 2026-10-05 01:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_newsarticle_companies"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="relevance",
            field=models.FloatField(
                blank=True,
                help_text="How much the article matters to the Indian market, from 0 to 1.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="scored_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Empty means not scored yet.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="sentiment_attempts",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Tries that failed. We stop after SENTIMENT_MAX_ATTEMPTS.",
            ),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="sentiment_model",
            field=models.CharField(
                blank=True,
                help_text="The LLM model that scored the article.",
                max_length=100,
            ),
        ),
    ]
