# Generated by Django 6.1.1 on 2026-10-09 05:59

from django.db import migrations, models


FEEDS = [('Business Standard', 'Markets', 'https://www.business-standard.com/rss/markets-106.rss'), ('Economic Times', 'Markets', 'https://economictimes.indiatimes.com/markets/rssfeeds/1977021501.cms'), ('Economic Times', 'Stocks', 'https://economictimes.indiatimes.com/markets/stocks/rssfeeds/2146842.cms'), ('Economic Times', 'IPO', 'https://economictimes.indiatimes.com/markets/ipos/fpos/rssfeeds/14655708.cms'), ('Mint', 'Markets', 'https://www.livemint.com/rss/markets'), ('Mint', 'Companies', 'https://www.livemint.com/rss/companies'), ('Moneycontrol', 'Top news', 'https://www.moneycontrol.com/rss/MCtopnews.xml'), ('Moneycontrol', 'Market reports', 'https://www.moneycontrol.com/rss/marketreports.xml'), ('Moneycontrol', 'Business', 'https://www.moneycontrol.com/rss/business.xml')]


def seed_feeds(apps, schema_editor):
    """Save the first feeds. After this, the feeds are edited on the Ops pages."""
    NewsFeed = apps.get_model("news", "NewsFeed")
    for source, name, url in FEEDS:
        NewsFeed.objects.get_or_create(url=url, defaults={"source": source, "name": name})


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_sentiment_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsFeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="The source name, for example Mint.", max_length=100
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the feed, for example Markets.",
                        max_length=100,
                    ),
                ),
                ("url", models.URLField(max_length=1000, unique=True)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_fetched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_new_count",
                    models.PositiveIntegerField(
                        default=0, help_text="New articles at the last run."
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True, help_text="Empty if the last run worked."
                    ),
                ),
            ],
            options={
                "ordering": ["source", "name"],
            },
        ),
        migrations.RunPython(seed_feeds, migrations.RunPython.noop),
    ]
