# Generated by Django 6.1.1 on 2026-10-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "symbol",
                    models.CharField(
                        help_text="NSE or BSE symbol.", max_length=50, unique=True
                    ),
                ),
                ("sector", models.CharField(blank=True, max_length=100)),
                ("screener_url", models.URLField(blank=True, max_length=500)),
                (
                    "screener_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Raw data from Screener.in."
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the Screener.in data was last fetched. Empty means never.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "companies",
                "ordering": ["name"],
            },
        ),
    ]
