# Generated by Django 6.1.1 on 2026-10-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="aliases",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Other names used in news, for example ["SBI", "State Bank of India"].',
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="screener_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Data from Screener.in. Empty until the first refresh.",
            ),
        ),
    ]
