# Generated by Django 6.1.1 on 2026-10-04 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[("mainboard", "Mainboard"), ("sme", "SME")],
                        default="mainboard",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("listed", "Listed"),
                        ],
                        db_index=True,
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                ("open_date", models.DateField(blank=True, null=True)),
                ("close_date", models.DateField(blank=True, null=True)),
                ("listing_date", models.DateField(blank=True, null=True)),
                (
                    "price_band_low",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "price_band_high",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("lot_size", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "issue_size_cr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Issue size in crore rupees.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "gmp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Grey market premium in rupees.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "subscription_times",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total subscription, in times.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        blank=True,
                        help_text="Our score for this IPO. Set by the scoring step.",
                        null=True,
                    ),
                ),
                ("source_url", models.URLField(blank=True, max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ipos",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-open_date", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "open_date"), name="unique_ipo_name_open_date"
                    )
                ],
            },
        ),
    ]
