# Generated by Django 6.1.1 on 2026-10-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ipo",
            name="gmp_updated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the GMP was last set or confirmed.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ipo",
            name="listing_gain_pct",
            field=models.FloatField(
                blank=True,
                help_text="Gain at the listing, in percent, compared with the upper price band.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ipo",
            name="listing_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price at the listing.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ipo",
            name="score_inputs",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="All the numbers that gave the score.",
            ),
        ),
        migrations.AddField(
            model_name="ipo",
            name="scored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ipo",
            name="subscription_updated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the subscription was last set or confirmed.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ipo",
            name="verdict",
            field=models.CharField(
                blank=True,
                choices=[
                    ("good", "Likely to do well"),
                    ("mixed", "Mixed"),
                    ("weak", "Unlikely to do well"),
                    ("unknown", "Not enough data"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="ipo",
            name="score",
            field=models.FloatField(
                blank=True,
                help_text="Our score for this IPO, from -1 to 1. Set by the scoring step.",
                null=True,
            ),
        ),
    ]
