# Generated by Django 6.1.1 on 2026-10-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipos", "0002_ipo_scoring_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="ipo",
            name="bse_code",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="ipo",
            name="isin",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name="ipo",
            name="nse_symbol",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
