# Generated by Django 6.1.1 on 2026-10-04 07:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="The date of the report.", unique=True),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        help_text="The full report text that is sent to users.",
                    ),
                ),
                (
                    "prediction",
                    models.CharField(
                        blank=True,
                        choices=[("up", "Up"), ("down", "Down"), ("flat", "Flat")],
                        max_length=10,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        blank=True,
                        help_text="From 0 to 1.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
