# Generated by Django 6.1.1 on 2026-10-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="The numbers and the lists behind the text. The web page uses them.",
            ),
        ),
    ]
